# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc3d8120bcd8a391decf8d2261b30b3e155b5c564ae72fdd37864aef4e5413c7ba1db52a87923617ef245d383bcf60dfcb458ca3ab5e28613685c0f71f8302bc

test:
  secret_key_base: 1dc25fc5854782c6161f581ddbb8f106439d3a6633afebdf38a05f01c546d4b0f703d988d2b0440ac943449b4dfbc76e8f0ec5e522bab3f7f70f4c94a959acc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
